services:
  curriculum-db:
    image: mysql:8.0
    container_name: curriculum-db
    restart: always
    networks:
      - curriculum-net
    environment:
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d

  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    command: start-dev
    networks:
      - curriculum-net
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8093:8080"

  ms-curriculum:
    build: './ms-curriculum'
    container_name: ms-curriculum
    depends_on:
      - curriculum-db
      - keycloak
      - ms-usuario
    networks:
      - curriculum-net
    environment:
      - DB_HOST=curriculum-db
      - DB_PORT=3306
      - DB_NAME=ms_curriculum
      - DB_USER=user_curriculum
      - DB_PASSWORD=admin
      - MS_USUARIO_URL=http://ms-usuario:8091
      - KEYCLOAK_ISSUER_URI=http://keycloak:8080/realms/curriculum
      - KEYCLOAK_JWK_SET_URI=http://keycloak:8080/realms/curriculum/protocol/openid-connect/certs
    ports:
      - "8090:8090"

  ms-usuario:
    build: './ms-usuario'
    container_name: ms-usuario
    depends_on:
      - curriculum-db
      - keycloak
    networks:
      - curriculum-net
    environment:
      - DB_HOST=curriculum-db
      - DB_PORT=3306
      - DB_NAME=ms_usuario
      - DB_USER=user_usuario
      - DB_PASSWORD=admin
      - KEYCLOAK_SERVER_URL=http://keycloak:8080
      - KEYCLOAK_REALM=curriculum
      - KEYCLOAK_ADMIN_CLIENT_ID=curriculum-app-admin
      - KEYCLOAK_ADMIN_CLIENT_SECRET=cJLeqvJ5KE8OUCPIUuIhULXmx3CCdwGO
      - KEYCLOAK_USER_CLIENT_ID=curriculum-app-user
      - KEYCLOAK_ISSUER_URI=http://keycloak:8080/realms/curriculum
      - KEYCLOAK_JWK_SET_URI=http://keycloak:8080/realms/curriculum/protocol/openid-connect/certs
    ports:
      - "8091:8091"

  ms-vagas:
    build: './ms-vagas'
    container_name: ms-vagas
    depends_on:
      - curriculum-db
      - keycloak
    networks:
      - curriculum-net
    environment:
      - DB_HOST=curriculum-db
      - DB_PORT=3306
      - DB_NAME=ms_vagas
      - DB_USER=user_vagas
      - DB_PASSWORD=admin
      - MS_USUARIO_URL=http://ms-usuario:8091
      - KEYCLOAK_ISSUER_URI=http://keycloak:8080/realms/curriculum
      - KEYCLOAK_JWK_SET_URI=http://keycloak:8080/realms/curriculum/protocol/openid-connect/certs
    ports:
      - "8092:8092"

  bff-curriculum:
    build: './bff-curriculum'
    container_name: bff-curriculum
    depends_on:
      - curriculum-db
      - ms-vagas
      - ms-curriculum
      - ms-usuario
    environment:
      - MS_CURRICULUM=http://ms-curriculum:8090
      - MS_USUARIO=http://ms-usuario:8091
      - MS_VAGAS=http://ms-vagas:8092
    networks:
      - curriculum-net
    ports:
      - "8080:8080"

networks:
  curriculum-net:
    driver: bridge

