server:
  port: 8090
spring:
  application:
    name: ms-curriculum
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:ms_curriculum}
    username: ${DB_USER:user_curriculum}
    password: ${DB_PASSWORD:admin}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8093/realms/curriculum}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:8093/realms/curriculum/protocol/openid-connect/certs}

feign:
  ms-usuario:
    url: ${MS_USUARIO_URL:http://localhost:8091}
    logger-level: ${FEIGN_MS_USUARIO_LOGGER_LEVEL:FULL}
    connect-timeout: ${FEIGN_MS_USUARIO_CONNECT_TIMEOUT:5000}
    read-timeout: ${FEIGN_MS_USUARIO_READ_TIMEOUT:10000}

logging:
  level:
    br.com.senac.mscurriculum: DEBUG
    br.com.senac.mscurriculum.client.MsUsuarioClient: DEBUG
